# Generated by Django 5.0 on 2023-12-12 05:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("useraccounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="userId",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=40,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
